print("Enter a of Pentagonal  prism: ")
a = float(input())
print("Enter Breadth of Pentagonal  prism: ")
b = float(input())
print("Enter Height of Pentagonal  prism: ")
h = float(input())
s= (5*a*b)+(5*b*h)
print("Surface area of the Pentagonal prism: ",s)
