print("Enter Length of Triangular  prism: ")
l = float(input())
print("Enter Breadth of Triangular  prism: ")
b = float(input())
print("Enter Height of Triangular  prism: ")
h = float(input())
s1=float(input("Enter s1: "))
s2=float(input("Enter s2: "))
s3=float(input("Enter s3: "))
a= b*h+l*(s1+s2+s3)
print("Surface area of the Triangular  prism: ",a)
